name: Documentation CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # build:
  #   name: Test Build
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [14.x]

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: npm install
  #     - run: npm run build

  deploy:
    name: Deployment to Github-pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: |
          git config --global user.name "Raktim Shrestha"
          git config --global user.email "raktim@rumsan.com"
      - run: yarn run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
